---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterblender-de-deployment
  labels:
    app: masterblender-de
spec:
  replicas: 2
  selector:
    matchLabels:
      app: masterblender-de
  template:
    metadata:
      labels:
        app: masterblender-de
    spec:
      containers:
        - name: website
          image: sommerfeldio/website-masterblender-de:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: masterbl-http
