---
apiVersion: v1
kind: Service
metadata:
  name: masterblender-de-service
spec:
  selector:
    app: masterblender-de
  ports:
    - port: 3888
      targetPort: masterbl-http
      protocol: TCP
  type: LoadBalancer
