---
version: "3.3"
services:

  k8s_prometheus:
    image: prom/prometheus:v2.43.0
    container_name: k8s_prometheus
    restart: unless-stopped
    volumes:
      - ./assets/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - /etc/timezone:/etc/timezone:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 3090:9090
    extra_hosts:
      - host.docker.internal:host-gateway

  k8s_grafana:
    image: grafana/grafana:9.2.15-ubuntu
    container_name: k8s_grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - k8s_prometheus
    volumes:
      - ./assets/provisioning/grafana:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway

  k8s_blackbox_exporter:
    image: prom/blackbox-exporter:v0.23.0
    container_name: k8s_blackbox_exporter
    restart: unless-stopped
    depends_on:
      - k8s_prometheus
    ports:
      - 3115:9115
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./assets/config/prometheus/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  k8s_node_exporter:
    image: prom/node-exporter:latest
    container_name: k8s_node_exporter
    restart: always
    command:
      - --path.rootfs=/host
      - --web.listen-address=:3100
    pid: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
      - /etc/timezone:/etc/timezone:ro

  k8s_cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: k8s_cadvisor
    restart: always
    ports:
      - 3110:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true

  k8s_portainer:
    image: portainer/portainer-ce:alpine
    container_name: k8s_portainer
    command: -H unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: always
    ports:
      - 3990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro

volumes:
  prometheus_data:
  grafana_data:
  portainer_data:
