# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "ubuntu/lunar64" # jammy = 22.04, lunar = 23,04
HOSTNAME = "k8s"
#IP = "192.168.56.42"

Vagrant.configure(2) do |config|

    config.vm.define HOSTNAME do |k8s|
        k8s.vm.box = IMAGE_NAME
        k8s.vm.hostname = HOSTNAME
        #k8s.vm.network :private_network, ip: IP

        k8s.vm.provider "virtualbox" do |v|
            v.memory = 1024*4
            v.cpus = 2
            v.customize ["modifyvm", :id, "--groups", "/vagrantboxes"]
            v.name = HOSTNAME
        end

        k8s.vm.provision "shell", path: "provision/configure.sh"
        k8s.vm.provision "shell", path: "provision/install-docker.sh"
        k8s.vm.provision "shell", path: "provision/install-minikube.sh"
        k8s.vm.provision "shell", path: "provision/install-kubectl.sh"

        k8s.vm.provision "shell", path: "services/vagrantbox/ops/start.sh"
        k8s.vm.provision "shell", path: "services/vagrantbox/minikube/start.sh"
        k8s.vm.provision "shell", path: "services/vagrantbox/minikube/deploy-demo-app.sh"

        # see src/main/services/vagrantbox/ops/docker-compose.yml
        k8s.vm.network "forwarded_port", host: 6100, guest: 9100
        k8s.vm.network "forwarded_port", host: 6110, guest: 9110
        k8s.vm.network "forwarded_port", host: 6990, guest: 9990

        # see src/main/services/vagrantbox/minikube/deploy-demo-app.sh
        k8s.vm.network "forwarded_port", host: 6080, guest: 6080
    end
end
